development:
  min_prefix_len: 3
production:
    min_prefix_len: 3
    searchd_file_path: "/var/www/cbcl/shared/sphinx"
    searchd_log_file: "/home/cbcl/sites/cbcl/current/log/searchd.log"
    query_log_file: "/home/cbcl/sites/cbcl/current/log/searchd.query.log"
    pid_file: "/var/www/cbcl/shared/searchd.production.pid"
test:
    min_prefix_len: 3