development:
  min_prefix_len: 3
production:
  min_prefix_len: 3
  # searchd_file_path: "/var/www/cbcl/shared/sphinx"
  searchd_log_file: "/var/www/cbcl/log/searchd.log"
  query_log_file: "/var/www/cbcl/log/searchd.query.log"
  pid_file: "/var/www/cbcl/shared/searchd.production.pid"
  config_file: "/var/www/cbcl/shared/config/production.sphinx.conf"
test:
  min_prefix_len: 3