development:
  min_prefix_len: 3
  config_file: "RAILS_ROOT/config/ENVIRONMENT.sphinx.conf"
  searchd_log_file: "RAILS_ROOT/log/searchd.log"
  query_log_file: "RAILS_ROOT/log/searchd.query.log"
  pid_file: "RAILS_ROOT/log/searchd.ENVIRONMENT.pid"
production:
    min_prefix_len: 3
    config_file: "RAILS_ROOT/config/ENVIRONMENT.sphinx.conf"
    searchd_log_file: "RAILS_ROOT/log/searchd.log"
    query_log_file: "RAILS_ROOT/log/searchd.query.log"
    pid_file: "RAILS_ROOT/log/searchd.ENVIRONMENT.pid"
test:
    min_prefix_len: 3
    config_file: "RAILS_ROOT/config/ENVIRONMENT.sphinx.conf"
    searchd_log_file: "RAILS_ROOT/log/searchd.log"
    query_log_file: "RAILS_ROOT/log/searchd.query.log"
    pid_file: "RAILS_ROOT/log/searchd.ENVIRONMENT.pid"